##
## This file can safely be deleted.
## The intention is just to show off the @promise-watch/smtp package
##

version: "3.7"

services:
  mailhog:
    image: mailhog/mailhog
    ports:
      - 8025:8025
      - 1025:1025
