apiVersion: v1
kind: Namespace
metadata:
  name: uptime-runs
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: uptime-runs
  namespace: uptime-runs
spec:
  minReadySeconds: 5
  replicas: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: uptime-runs
  template:
    metadata:
      labels:
        app: uptime-runs
    spec:
      restartPolicy: Always
      containers:
        - name: uptime-runs
          image: ghcr.io/jasonraimondi/promise-watch-example:latest
          command:
            - pnpm
            - start
          resources:
            limits:
              cpu: 2000m
              memory: 2048Mi
            requests:
              cpu: 1000m
              memory: 1024Mi
