name: Test

on:
  push:
  pull_request:
  release:

env:
  NODE_VERSION: 16.13.2
  PNPM_VERSION: 6.22.2

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2
        with:
          version: ${{ env.PNPM_VERSION }}
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml
      - run: pnpm it --frozen-lockfile --production false

  publish:
    if: github.ref_name == 'master' || github.ref_name == 'next'
    needs: [ test ]
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2
        with:
          version: ${{ env.PNPM_VERSION }}
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml
          registry-url: 'https://registry.npmjs.org'
      - run: pnpm i --frozen-lockfile --production false
      - run: pnpm publish --recursive --filter="@promise-watch/core" --access=public --tag next
