name: Test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2
        with:
          version: 6.22.2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.13.2
          registry-url: https://registry.npmjs.org/
      - run: pnpm it --frozen-lockfile --production false
